version: '3.1'
services:
  db:
    container_name: ordersDbSlave
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      # just if you also want to access it directly from you host
      # node neede for phpmyadmin
      - "3308:3306"
  phpmyadmin:
    container_name: ordersAdminSlave
    restart: always
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8083:80"
